### ISSUE TITLE
mmpose and mmcv version

### ISSUE THREAD

**Issue by pengzhansun** [aim-uofa/Poseur#18]
Thanks for sharing this awesome work, but I encountered with some issues when trying to use this method. May I know the version of mmpose and mmcv you use?

**Comment by YongtaoGe** [comment]
```
mmcv-full==1.6.0
mmpose==0.28.0
```

**Comment by pengzhansun** [comment]
Hi @YongtaoGe , thanks for your quick reply! I use the correct version but then I met the same problem as in [this issue](https://github.com/aim-uofa/Poseur/issues/17#issuecomment-1528677812). I just download these two packages through pip install. Is that the correct way to utilize these tools?

**Comment by YongtaoGe** [comment]
Instead of installing the official mmpose, you should install the Poseur with:
```
pip install -e .
```
