### ISSUE TITLE
Prediction uncertainty estimation.

### ISSUE THREAD

**Issue by gs-ren** [aim-uofa/Poseur#2]
It seems the  implement of Prediction uncertainty estimation which mentioned in  Chapter 3.3 is missing. @YongtaoGe

**Comment by YongtaoGe** [comment]
Hi, @gs-ren thanks for your interest in our paper. the uncertainty estimation is implemented [here](https://github.com/aim-uofa/Poseur/blob/9358ed54dc597f9c46b114e8f57b018b5af55ddd/mmpose/models/detectors/poseur.py#L227)

**Comment by gs-ren** [comment]
> Hi, @gs-ren thanks for your interest in our paper. the uncertainty estimation is implemented [here](https://github.com/aim-uofa/Poseur/blob/9358ed54dc597f9c46b114e8f57b018b5af55ddd/mmpose/models/detectors/poseur.py#L227)

Thank you for your reply！In this [implement](https://github.com/aim-uofa/Poseur/blob/9358ed54dc597f9c46b114e8f57b018b5af55ddd/mmpose/models/detectors/poseur.py#L231), what does the  scale number 0.7 mean？

**Comment by YongtaoGe** [comment]
It is just a hyperparameter that scales the keypoint score, we set it to 0.7 by default.
