### ISSUE TITLE
The URL for downloading the poseur_mobilenetv2_coco_256x192 model is linked to the poseur_res50_coco_256x192 model

### ISSUE THREAD

**Issue by PINTO0309** [aim-uofa/Poseur#3]
Thank you for making this wonderful repository available to the public.

The URL for `poseur_mobilenetv2_coco_256x192` appears to be wrong because downloading a checkpoint for `poseur_mobilenetv2_coco_256x192` downloads a checkpoint for `poseur_res50_coco_256x192`.

- COCO Keypoint Detection Results
https://github.com/aim-uofa/Poseur#coco-keypoint-detection-results

- `poseur_mobilenetv2_coco_256x192` URL
https://cloudstor.aarnet.edu.au/plus/s/UXr1Dn9w6ja4fM9/download

- `poseur_res50_coco_256x192` URL
https://cloudstor.aarnet.edu.au/plus/s/UXr1Dn9w6ja4fM9/download

![image](https://user-images.githubusercontent.com/33194443/187100716-a596689f-89f7-48f5-b84a-b50f5d546660.png)

Thank you.

**Comment by YongtaoGe** [comment]
@PINTO0309 Sorry for the wrong link of MobileNet v2. We would fix it today.

**Comment by maowayne123** [comment]
thank you for pointing out this issue. we already replace the wrong link. you can download it again. it should be fixed now.

**Comment by PINTO0309** [comment]
Thank you!
